name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      pgbackrest_version:
        description: 'pgBackrest version'
        required: true
        default: '2.57.0'
        type: string

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  VERSION_TAG: ${{ github.event.inputs.pgbackrest_version }}
  DEFAULT_POSTGRES_MAJOR: '18'

jobs:
  build:
    name: Build image (pg${{ matrix.pg_major }} • ${{ matrix.platform }})
    runs-on: ${{ contains(matrix.platform, 'arm64') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        pg_major: ['16', '17', '18']
        platform: ['linux/amd64', 'linux/arm64']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Prepare build variables
        run: |
          platform=${{ matrix.platform }}
          pg_major=${{ matrix.pg_major }}
          platform_pair=${platform//\//-}
          echo "PLATFORM_PAIR=${platform_pair}" >> $GITHUB_ENV
          echo "PG_MAJOR=${pg_major}" >> $GITHUB_ENV
          echo "TEST_TAG=pgbackrest-test-${pg_major}-${platform_pair}" >> $GITHUB_ENV
          echo "CACHE_SCOPE=pgbackrest-${pg_major}-${platform_pair}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image for smoke test
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: |
            PGBACKREST_VERSION=${{ env.VERSION_TAG }}
            POSTGRES_MAJOR=${{ env.PG_MAJOR }}
          cache-from: type=gha,scope=${{ env.CACHE_SCOPE }}
          cache-to: type=gha,scope=${{ env.CACHE_SCOPE }},mode=max

      - name: Smoke test (${{ matrix.platform }})
        run: |
          docker run --rm ${{ env.TEST_TAG }} pgbackrest --version

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          tags: ${{ env.IMAGE_NAME }}
          build-args: |
            PGBACKREST_VERSION=${{ env.VERSION_TAG }}
            POSTGRES_MAJOR=${{ env.PG_MAJOR }}
          cache-from: type=gha,scope=${{ env.CACHE_SCOPE }}
          cache-to: type=gha,scope=${{ env.CACHE_SCOPE }},mode=max

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests/${{ env.PG_MAJOR }}
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${{ env.PG_MAJOR }}/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-pg${{ env.PG_MAJOR }}-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/${{ env.PG_MAJOR }}
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Publish multi-arch manifest (pg${{ matrix.pg_major }})
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        pg_major: ['16', '17', '18']
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-pg${{ matrix.pg_major }}-*
          merge-multiple: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list
        working-directory: ${{ runner.temp }}/digests
        run: |
          set -euo pipefail
          image=${{ env.IMAGE_NAME }}
          version=${{ env.VERSION_TAG }}
          pg_major=${{ matrix.pg_major }}

          declare -A seen=()
          args=()
          while IFS= read -r -d '' path; do
            digest=$(basename "$path")
            if [[ ! "$digest" =~ ^[0-9a-f]{64}$ ]]; then
              continue
            fi
            if [[ -n "${seen[$digest]:-}" ]]; then
              continue
            fi
            seen[$digest]=1
            args+=("${image}@sha256:${digest}")
          done < <(find . -mindepth 1 -maxdepth 2 -print0)

          if [ "${#args[@]}" -eq 0 ]; then
            echo "No digests found for PostgreSQL ${pg_major}" >&2
            exit 1
          fi

          tags=(
            -t ${image}:${version}-pg${pg_major}
            -t ${image}:pg${pg_major}
          )
          if [ "${pg_major}" = "${{ env.DEFAULT_POSTGRES_MAJOR }}" ]; then
            tags+=(
              -t ${image}:${version}
              -t ${image}:latest
            )
          fi

          docker buildx imagetools create "${tags[@]}" "${args[@]}"

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}-pg${{ matrix.pg_major }}
